### ISSUE TITLE
Incorrect comparison

### ISSUE THREAD

**Issue by foleyj2** [eoyilmaz/timecode#14]
I think there might be an error on the comparison code for sub-fractional second timecodes.
These are timecodes I was given from ffmpeg.

`#!/usr/bin/python
from timecode import Timecode

tc3 = Timecode(25, '00:20:25.92')
tc5 = Timecode(25, '00:20:25.72')
if tc3 > tc5:
    print "tc3 is bigger than tc5"
if tc3 < tc5:
    print "tc5 is bigger than tc3"`

prints out that tc5 is bigger on my machine.

**Comment by eoyilmaz** [comment]
Fixed with your merge request in 13971288b47cd5236691030d73ffff7ce1753c3b
