### ISSUE TITLE
TC to frameCount

### ISSUE THREAD

**Issue by moskiteau** [eoyilmaz/timecode#18]
https://github.com/eoyilmaz/timecode/blob/38b91fa1ab8d7038ce83bea529f555905fe8df20/timecode/__init__.py#L206

Why do you add 1 frame at the end?

**Comment by iluvcapra** [comment]
I think it's meant to be an inclusive count -- in film days we'd call it an "outside-outside" count.

`frames` is the address of the last frame and `frame_count` is the total number of occupied frames.

**Comment by moskiteau** [comment]
I saw it after but you also remove 1 frame, line 234

Thank you
