### ISSUE TITLE
float doesn't use frame_number

### ISSUE THREAD

**Issue by merlink01** [eoyilmaz/timecode#21]
As example:

seconds = 39.472766666666665
tc = Timecode(('30000', '1001'),seconds )
print(tc.float)
returns 39.50617283950618

if I change:

    def float(self):
        """returns the seconds as float
        """
        return (self.frames - 1)  / float(self.framerate)

I get 39.47280613947281.

So the float function doesn't calculate the frame_number.

**Comment by eoyilmaz** [comment]
I ran the following test code:

```python
from timecode import Timecode
seconds = 39.472766666666665
tc = Timecode(('30000', '1001'), start_seconds=seconds)
print(tc)
# returns: 00:00:39;13
print(tc.frames)
# returns: 1184
print(tc.float)
# returns: 39.46666666666667
```

which seems ok to me (and also to DaVinci Resolve).
