### ISSUE TITLE
Discarding '23.98' framerate in @framerate.setter?

### ISSUE THREAD

**Issue by morganwl** [eoyilmaz/timecode#26]
Is there a reason that, on line 129, the framerate setter sets framerate **and** _init_framerate to 24, instead of keeping the original framerate?

`        elif framerate in ['23.976', '23.98']:
            framerate = '24'
            self._int_framerate = 24`

While I appreciate that the frames_to_tc and tc_to_frames results are the same regardless, there are lots of circumstances where distinguishing between true 24 and pulldown timecodes is important.

**Comment by eoyilmaz** [comment]
Yes I think you're right the ``framerate = '24'`` shouldn't be there.

Also your question lead me to a discovery of a huge bug in 29.97 NDF and 59.94 NDF calculations. I've fixed it. Added new test cases to cover those bugs, all confirmed with by using DaVinci Resolve as a calculator.
