### ISSUE TITLE
Frame validation breaks timecode manipulation

### ISSUE THREAD

**Issue by SimonWilkinson** [eoyilmaz/timecode#31]
Hi,

I've got a long standing application which uses the timecode library to manipulate timecode offsets. Essentially we do

```
a = Timecode('25', timecode1);
b = Timecode('25', timecode2);
offset = a - b;
c = Timecode('25', timecode3) + offset;
```

This usage breaks with 1.2.3 when 'a' and 'b' are identical - the validation which insists frames has to be more than 0 causes a type error on the offset computation.

**Comment by eoyilmaz** [comment]
Okay I fixed the code in a weird way. It doesn't break the tests. But I didn't like the idea. So basically what I do is to return an integer if the subtract results a 0 or less frames. But what I don't like about it is that the ``__sub__`` method now returns either an integer or a Timecode and I really didn't like this incosistency.

What I want to do is to return a Timecode instance by using the ``abs(subtracted_frames)`` and raise an error if the result yields to 0 frames. This way it will always return a Timecode instance which has correct amount of frames. But you'll probably need to change your code so the c will be either calculated by:
```python
c = Timecode('25', timecode3) + offset
```
or by:
```python
c = Timecode('25', timecode3) - offset
```

**Comment by eoyilmaz** [comment]
Okay I released v1.2.5 with this change. Can you please, check it with your use case considering my previous comment.

**Comment by aki-sud** [comment]
Hi,
Also, could you please explain what should be the result when 2 identical timecodes are subtracted.

**Comment by eoyilmaz** [comment]
After 85901b00 subtracting two identical timecodes will raise a ``ValueError`` which you need to catch in your code.
