### ISSUE TITLE
Float property inaccurate?

### ISSUE THREAD

**Issue by mvanherk** [eoyilmaz/timecode#36]
I could be wrong but I think the float property is not returning the correct value:

https://github.com/eoyilmaz/timecode/blob/bde846369039adb72d028e9e5234c6e655fdcde8/timecode/__init__.py#L532

I'm working with 23.976 timecode and this property seems to be giving me incorrect results, I had to change it to:
`return float(self.frame_number) / (float(24000) / 1001)
`

So _frame_number_ instead of _frames_ to use the 0-based number rather than 1-based. 24000/1001 is not really necessary in most cases, but at large timecode values you may lose some time when dividing by 23.976

**Comment by eoyilmaz** [comment]
For the first part of your question, I'm thinking in this way (and this library is written accordingly), by definition a ``timecode`` is a label that we give to a single frame of a movie/media clip. So, if we have a frame and we gave a timecode (a label) to that frame, it means that we are representing a part of the clip with that frame, and that single frame, albeit not moving (don't show something moving), is reprenting a portion of the clip, so the duration, which is the ``float()`` functions return value is representing can not be 0. Again we have a frame, So we cannot use ``frame_number`` for ``float()`` function. So for the frame with timecode 00:00:00:00 the duration is 1/FPS seconds and not 0/FPS.

On the other hand, you are right on pointing that the fraction will be better to use there, so, I suggest that you use fractional frame rates and also we need to update ``float()`` to use fractional frame rate if available.
