### ISSUE TITLE
Python module seems not to convert SMPTE timecode to seconds.milliseconds format correctly 

### ISSUE THREAD

**Issue by Vincent-Dabouineau** [eoyilmaz/timecode#38]
When using module to convert a SMPTE timecode 00:00:00:00 to seconds.milliseconds format, the behavior is incorrect e.g the result is 0.04 and not 0.00 as expected (which is corresponding to the real playhead position on a timeline) :

![979e48e0-f552-4e88-a1eb-86ae13d77762](https://user-images.githubusercontent.com/7533232/158763426-19468371-73a3-44c9-8549-51ec632eff1e.jpg)

When using the module in a broadcast production environment, where the frame accuracy is mandatory, it smell like a real problem!

**Comment by eoyilmaz** [comment]
Sorry but your assumption is not correct.

You see, one frame shows the accumulated result of a certain amount of time that has passed (exposure time if you will), so if we have a frame, that means a certain amount of time has passed. The timecode is nothing but a label, and ``00:00:00:00`` is the label we generally give to the first frame (or frame 0 which is another label). But it doesn't mean 0 seconds has passed.

You can also think in terms of clip length. What is the clip length of a 1 frame clip, is it 0 seconds, no, it is 1/FPS seconds that is 0.04 seconds in your case. Does it make sense?

As a side note, in an NLE, the creator of that program generally puts the playhead graphic (the vertical line), visually at the edge of the box representing the clip, this may lead people to think that 0 seconds has passed. But as I explained above this is not correct a correct assumption.
