### ISSUE TITLE
Read a timecode source

### ISSUE THREAD

**Issue by MilkMGN** [eoyilmaz/timecode#49]
Hello, 

I've looked around for a while to read the timecode data coming in off of an audio source, but there are no libraries capable of doing this it seems. Is there an example available somewhere/ is this something that is being looked into being added? 

Thank you.

**Comment by eoyilmaz** [comment]
It is not of this libraries intent to parse data from an audio source. I see there are other Python libraries that can parse LTC data: https://github.com/nocarryr/python-ltc
