### ISSUE TITLE
Why does thsi library not support arbitrary FPS/Framerate?

### ISSUE THREAD

**Issue by RalfReddings** [eoyilmaz/timecode#50]
I am impressed with the library, it appears to be a very thorough effort.

But I cant understand why you limited it to a few framerates tough. There is not even support for `12` fps.

I am a traditional animator. And I am looking for a means to calculate potential animations for planning reasons as well as for variety of other reasons, such as matching 2D animations against live footage/3D etc. This often means I am working with `12` or `24`.

When I say arbitrary framerates, This site, [Frames to Timecode Calculator](https://www.omnicalculator.com/other/frames-to-timecode?c=GBP&v=fpses:12,frames:1000), lets you input any framerate and frame count to get a Timecode.

Perhaps this is to do the with Drop-Frame format, if so then can we not just get support for NDF Timecodes to have arbitrary framerates?

**Comment by eoyilmaz** [comment]
I'm not the original designer, and yes we can do it, we can at least add 12 FPS so that your need is mitigated.

**Comment by RalfReddings** [comment]
I see. Well, I am very glad to hear that your open to having 12 FPS in the future. I look forward to it for sure. Thank you.

**Comment by eoyilmaz** [comment]
Ah now I see, I've been away from this project for a while and really forgot the details about the inner workings, so I didn't realize in the first place, but we already have arbitrary frame rates support:

```python
>>> from timecode import Timecode
>>> tc1 = Timecode(12)
>>> tc1.framerate
'12'
>>> tc2 = Timecode("12")
>>> tc1 == tc2
True
```

So I'm closing this issue.

**Comment by RalfReddings** [comment]
@eoyilmaz  hmm interesting. I remember trying something similar and getting errors. I will have to double check then. Thank you for this.
