### ISSUE TITLE
Why do frames have to be larger than 0?

### ISSUE THREAD

**Issue by octimot** [eoyilmaz/timecode#51]
Hey there!

In the `frames.setter`, the [code](https://github.com/eoyilmaz/timecode/blob/88797fa3958a514214468c6b561d79ce83994471/timecode/__init__.py#L122C7-L126) raises a ValueError if the number of frames `frames <= 0:`

However, I think for specific operations, for e.g.  subtractions, even negative frame numbers might be useful as result.

In a somewhat similar manner, the `__init__` [code](https://github.com/eoyilmaz/timecode/blob/88797fa3958a514214468c6b561d79ce83994471/timecode/__init__.py#L91) also throws a ValueError if `start_seconds == 0`. Here, I think it might be useful to simply let 0 seconds pass and use the default value `self.frames = self.tc_to_frames('00:00:00:00')`

I can, of course, deal with both issues before passing values to Timecode (or in my own fork).

But, is there a particular reason why the use-case scenarios are restricted to `frames <= 0`?

Thanks for keeping this repo alive!
Cheers!

**Comment by octimot** [comment]
Coming back with a note after reading your comment on pull https://github.com/eoyilmaz/timecode/pull/27:

> I had to revert this because one of the commits are forcing the `start_seconds` option to be 0 and it is meaningless. A TimeCode can newer be 0 seconds in length. People mix the concept of TimeCode with something else. A TimeCode of 00:00:00:00 shows a single frame which can not correspond to 0 seconds length of duration. It is at least 1/FPS seconds in length.


I do agree that frame 0 is meaningless when you're trying to translate Timecode to a particular frame.

However, in the context of navigation or positioning within a video, using for e.g. a timecode of `00:00:00:00` to represent the very beginning of the video (frame 0) makes sense. Similarity, when you're trying to command NLEs that support Timecodes or frames beyond `frame >=0 ` for navigation, this, again would be useful. Or, when you're exporting EDL/XML/etc. for importing into NLEs.

In these cases, while the Timecode itself may not represent an actual frame of video, it does serve as a useful reference, a non-restrictive approach, where timecodes `00:00:00:00` and `00:00:00:01` translate to the same frame could work, in my view.

Second, I was mentioning earlier subtractions - again, when you're simply trying to see the mathematical difference between two timecodes, negative frames might also be useful...

Cheers!

**Comment by octimot** [comment]
@cubicibo 

Yes, I agree... using the same frame number was an hastly proposal, so the only way that would work would be if the class would store `00:00:00:00` as `frames=0`.

But I still see the purpose of returning `00:00:00:00` for navigation or positioning purposes as I mentioned.

For e.g. I'm dealing often with conversion from EDL to XML (sequences) or SRT to AVID DS (subtitles), and they all support using `00:00:00:00` as clip in points, for instance.

> What you are describing is a more elaborate class that inherits Timecode or makes extensive use of it. e.g ChapterMark. It would includes your very own code to suits your specific needs, while relying on a solid base for standard timecode operations.

I'm definitely going in this direction if this would't work for the `Timecode` package, but I wanted to understand if there is something inherently wrong with having frames equal or even smaller than 0 in timecodes and what principles I'm breaking.

**Comment by cubicibo** [comment]
>[...] they all support using 00:00:00:00 as clip in points, for instance.

`00:00:00:00` is a valid SMPTE timecode and can be instantiated with this Python package. Your mix-up comes from vastly different usages of timecodes, and it being tied to timestamps. A chapter mark is classically a **timestamp** specifying the play-back time to resume at. As a timecode, the system shall resume at, and display, the specified frame. However, drawing this frame would still require $frame\textunderscore{}duration = fps^{-1}$ seconds. Once the frame display, $t_{f_i} + frame\textunderscore{}duration$ has elapsed, while it was loaded at $t_{f_i}$.

So, under the hood, software using TC as chapters marks must load the frame before its presentation timestamp. They have to seek one frame backward:
```python3
def find_first_frame_at_chapter_tc(clip: list[Frame], chapter_tc: Timecode) -> Optional[Frame]:
    return next(filter(lambda frame: PTS(frame) >= chapter_tc.float - frame_duration, clip), None)
``` 

Essentially you want to work with timestamps internally for your chapter marks and then convert to TC to suits your needs. The code would look like this, if you only deal with standardized framerates like 23.98, 24, 29.97, 59.94...
```python3
def s2tc(s: float, fps: float) -> str:
    #Add 1e-8 to avoid wrong rounding
    return str(Timecode(round(fps, 2), start_seconds=s+1/fps+1e-8))

def tc2s(tc: str, fps: float) -> float:
    fps = round(fps, 2)
    return round(Timecode(fps, tc).float - Timecode(fps, '00:00:00:00').float, 5)
```

**Comment by octimot** [comment]
Thank you for taking the time to explain this @cubicibo !

> 00:00:00:00 is a valid SMPTE timecode and can be instantiated with this Python package. Your mix-up comes from vastly different usages of timecodes, and it being tied to timestamps. 

Right! The distinction between **timecode** and **timestamp** (and presentation timestamp) is essential for seeing the problem. In other words, if it looks like **timecode**, it's not necessarily **timecode**!

It's clearer to me that the mistake I was making comes from the fact that I was not just making use of the SMPTE timecode representation of the object, but also performing maths with the objects which were leading to results that looked weird to me, for e.g.:
```
tc = Timecode('24', '00:00:00:00')
tc2 = Timecode('24', '00:00:00:00')

tc3 = tc + tc2

print(tc3)  # = 00:00:00:01 instead of 00:00:00:00 (what I was expecting)
```

Cheers!

**Comment by eoyilmaz** [comment]
@octimot regarding to your last example, and to make it clearer for people reading it, tc3 is the combination of two single frame timecodes and thus constains 2 frames and represents a timecode of 2 frames and `00:00:00:01` totally makes sense to me as the first frame's time code is `00:00:00:00` and the second frame's time code is `00:00:00:01`...
