### ISSUE TITLE
Type Hints!

### ISSUE THREAD

**Issue by austinwitherspoon** [eoyilmaz/timecode#53]
I love type hints and how they help dev tools (using mypy or pyright to catch errors for me!) I know that type hints are loved by everybody - so totally fair if you want to close this issue.

Now that python 2 is end of life, I think it would be great to add type hints to this package and update it so it's python 3.7+.

Currently I'm trying to use this in a project that we run mypy on, but mypy complains when you try to use dependencies that don't have type hints!

If you're on board with the idea, I'm happy to do the work and put in a PR. (I'm already doing the work in a stubs file for this on my project to appease mypy anyway)

**Comment by eoyilmaz** [comment]
Hey @austinwitherspoon yeah that's a very good idea and if you have time you are welcomed to add it 👍
