### ISSUE TITLE
Inconsistent Duration Results in testing.

### ISSUE THREAD

**Issue by jdrx99** [eoyilmaz/timecode#57]
from timecode import Timecode

# Set FPS as a constant for all experiments
FPS = '24'

# Test scenarios:
# 1. No frame difference (start and end are the same)
#    - Input: Start TC = '00:00:00:00', End TC = '00:00:00:00'
#    - Expected Result: Duration = 1 frame

tc_in_0 = Timecode(FPS, '00:00:00:00')
tc_out_0 = Timecode(FPS, '00:00:00:00')
duration_frames_0 = (tc_out_0 - tc_in_0).frames
print(f"Duration for no frame difference (from {tc_in_0} to {tc_out_0}): {duration_frames_0} frames")
assert duration_frames_0 == 1, "Duration for identical start and end timecodes should be 1 frame"

# 2. 1 frame apart
#    - Input: Start TC = '00:00:00:00', End TC = '00:00:00:01'
#    - Expected Result: Duration = 2 frames

tc_in_1 = Timecode(FPS, '00:00:00:00')
tc_out_1 = Timecode(FPS, '00:00:00:01')
duration_frames_1 = (tc_out_1 - tc_in_1).frames
print(f"Duration for 1 frame apart (from {tc_in_1} to {tc_out_1}): {duration_frames_1} frames")
assert duration_frames_1 == 2, "Duration for 1 frame apart should be 2 frames"

# 3. 2 frames apart
#    - Input: Start TC = '00:00:00:00', End TC = '00:00:00:02'
#    - Expected Result: Duration = 3 frames

tc_in_2 = Timecode(FPS, '00:00:00:00')
tc_out_2 = Timecode(FPS, '00:00:00:02')
duration_frames_2 = (tc_out_2 - tc_in_2).frames
print(f"Duration for 2 frames apart (from {tc_in_2} to {tc_out_2}): {duration_frames_2} frames")
assert duration_frames_2 == 3, "Duration for 2 frames apart should be 3 frames"

# 4. 1 second apart (24 frames apart)
#    - Input: Start TC = '00:00:00:00', End TC = '00:00:01:00'
#    - Expected Result: Duration = 24 frames

tc_in_3 = Timecode(FPS, '00:00:00:00')
tc_out_3 = Timecode(FPS, '00:00:01:00')
duration_frames_24 = (tc_out_3 - tc_in_3).frames
print(f"Duration for 1 second apart (from {tc_in_3} to {tc_out_3}): {duration_frames_24} frames")
assert duration_frames_24 == 24, "Duration for 1 second apart at 24fps should be 24 frames"

---

Getting Error

PS E:\TimeCode_Tools> & E:/mc/envs/TC/python.exe e:/TimeCode_Tools/001Test.py
Traceback (most recent call last):
  File "e:\TimeCode_Tools\001Test.py", line 13, in <module>
    duration_frames_0 = (tc_out_0 - tc_in_0).frames
                         ~~~~~~~~~^~~~~~~~~
  File "E:\mc\envs\TC\Lib\site-packages\timecode\__init__.py", line 745, in __sub__
    tc = Timecode(self.framerate, frames=abs(subtracted_frames))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\mc\envs\TC\Lib\site-packages\timecode\__init__.py", line 97, in __init__
    self.frames = frames
    ^^^^^^^^^^^
  File "E:\mc\envs\TC\Lib\site-packages\timecode\__init__.py", line 132, in frames
    raise ValueError(
ValueError: Timecode.frames should be a positive integer bigger than zero, not 0

---

Please guide me.
am confused when to use .frames and .frame_number.

I think .frames is best for final result but not sure how to implement.

**Comment by jdrx99** [comment]
from timecode import Timecode

# Set FPS as a constant for all tests
FPS = '24'

def calculate_duration(tc_in, tc_out):
    """Calculate the duration between two timecodes, including the start frame if needed."""
    if tc_in == tc_out:
        return 1  # Identical timecodes result in 1 frame

    # Calculate the frame difference
    frame_difference = (tc_out - tc_in).frames

    # Add 1 only if the timecodes are within the same second
    if frame_difference < int(FPS):
        return frame_difference + 1

    return frame_difference

def assert_duration(scenario_num, description, expected, duration):
    """Print and assert the duration with scenario numbering for easy identification."""
    print(f"Scenario {scenario_num}: {description} => {duration} frames")
    assert duration == expected, f"Scenario {scenario_num}: {description} should be {expected} frames"

# Test Cases

# 1. Identical timecodes
tc_in_0 = Timecode(FPS, '00:00:00:00')
tc_out_0 = Timecode(FPS, '00:00:00:00')
assert_duration(1, "Duration for identical timecodes", 1, calculate_duration(tc_in_0, tc_out_0))

# 2. 1 frame
tc_in_1 = Timecode(FPS, '00:00:00:00')
tc_out_1 = Timecode(FPS, '00:00:00:01')
assert_duration(2, "Duration for 1 frame", 2, calculate_duration(tc_in_1, tc_out_1))

# 3. 2 frames
tc_in_2 = Timecode(FPS, '00:00:00:00')
tc_out_2 = Timecode(FPS, '00:00:00:02')
assert_duration(3, "Duration for 2 frames", 3, calculate_duration(tc_in_2, tc_out_2))

# 4. 1 second apart (24 frames)
tc_in_3 = Timecode(FPS, '00:00:00:00')
tc_out_3 = Timecode(FPS, '00:00:01:00')
assert_duration(4, "Duration for 1 second apart", 24, calculate_duration(tc_in_3, tc_out_3))

# 5. 1 second and 1 frame apart (25 frames)
tc_in_4 = Timecode(FPS, '00:00:00:00')
tc_out_4 = Timecode(FPS, '00:00:01:01')
assert_duration(5, "Duration for 1 second and 1 frame apart", 25, calculate_duration(tc_in_4, tc_out_4))

# Additional Scenarios with Start TC as 01:00:00:01

# 6. Identical timecodes at 01:00:00:01
tc_in_5 = Timecode(FPS, '01:00:00:01')
tc_out_5 = Timecode(FPS, '01:00:00:01')
assert_duration(6, "Duration for identical timecodes at 01:00:00:01", 1, calculate_duration(tc_in_5, tc_out_5))

# 7. 1 frame from 01:00:00:01 to 01:00:00:02
tc_in_6 = Timecode(FPS, '01:00:00:01')
tc_out_6 = Timecode(FPS, '01:00:00:02')
assert_duration(7, "Duration for 1 frame from 01:00:00:01", 2, calculate_duration(tc_in_6, tc_out_6))

# 8. 2 frames from 01:00:00:01 to 01:00:00:03
tc_in_7 = Timecode(FPS, '01:00:00:01')
tc_out_7 = Timecode(FPS, '01:00:00:03')
assert_duration(8, "Duration for 2 frames from 01:00:00:01", 3, calculate_duration(tc_in_7, tc_out_7))

# 9. 1 second apart from 01:00:00:01 to 01:00:01:00 (24 frames)
tc_in_8 = Timecode(FPS, '01:00:00:01')
tc_out_8 = Timecode(FPS, '01:00:01:00')
assert_duration(9, "Duration for 1 second apart from 01:00:00:01", 24, calculate_duration(tc_in_8, tc_out_8))

# 10. 1 second and 1 frame from 01:00:00:01 to 01:00:01:02 (25 frames)
tc_in_9 = Timecode(FPS, '01:00:00:01')
tc_out_9 = Timecode(FPS, '01:00:01:02')
assert_duration(10, "Duration for 1 second and 1 frame from 01:00:00:01", 25, calculate_duration(tc_in_9, tc_out_9))

print("All tests passed successfully!")


---

This works fine!
I was using the wrong syntax and method.

Results:

PS E:\TimeCode_Tools> & E:/mc/envs/TC/python.exe e:/TimeCode_Tools/002_TEST.py
Scenario 1: Duration for identical timecodes => 1 frames
Scenario 2: Duration for 1 frame => 2 frames
Scenario 3: Duration for 2 frames => 3 frames
Scenario 4: Duration for 1 second apart => 24 frames
Scenario 5: Duration for 1 second and 1 frame apart => 25 frames
Scenario 6: Duration for identical timecodes at 01:00:00:01 => 1 frames
Scenario 7: Duration for 1 frame from 01:00:00:01 => 2 frames
Scenario 8: Duration for 2 frames from 01:00:00:01 => 3 frames
Scenario 9: Duration for 1 second apart from 01:00:00:01 => 24 frames
Scenario 10: Duration for 1 second and 1 frame from 01:00:00:01 => 25 frames
All tests passed successfully!

**Comment by jdrx99** [comment]
from timecode import Timecode

# Set FPS as a constant for all tests
FPS = '24'

def calculate_duration(tc_in, tc_out):
    """Calculate the duration between two timecodes, including the start frame if needed."""
    if tc_in == tc_out:
        return 1  # Identical timecodes result in 1 frame

    # Calculate the frame difference
    frame_difference = (tc_out - tc_in).frames

    # Add 1 only if the timecodes are within the same second
    if frame_difference < int(FPS):
        return frame_difference + 1

    return frame_difference

def assert_duration(scenario_num, description, expected, duration):
    """Print and assert the duration with scenario numbering for easy identification."""
    print(f"Scenario {scenario_num}: {description} => {duration} frames")
    assert duration == expected, f"Scenario {scenario_num}: {description} should be {expected} frames"

# Test Cases

# 1. Identical timecodes
tc_in_0 = Timecode(FPS, '00:00:00:00')
tc_out_0 = Timecode(FPS, '00:00:00:00')
assert_duration(1, "Duration for identical timecodes", 1, calculate_duration(tc_in_0, tc_out_0))

# 2. 1 frame
tc_in_1 = Timecode(FPS, '00:00:00:00')
tc_out_1 = Timecode(FPS, '00:00:00:01')
assert_duration(2, "Duration for 1 frame", 2, calculate_duration(tc_in_1, tc_out_1))

# 3. 2 frames
tc_in_2 = Timecode(FPS, '00:00:00:00')
tc_out_2 = Timecode(FPS, '00:00:00:02')
assert_duration(3, "Duration for 2 frames", 3, calculate_duration(tc_in_2, tc_out_2))

# 4. 1 second apart (24 frames)
tc_in_3 = Timecode(FPS, '00:00:00:00')
tc_out_3 = Timecode(FPS, '00:00:01:00')
assert_duration(4, "Duration for 1 second apart", 24, calculate_duration(tc_in_3, tc_out_3))

# 5. 1 second and 1 frame apart (25 frames)
tc_in_4 = Timecode(FPS, '00:00:00:00')
tc_out_4 = Timecode(FPS, '00:00:01:01')
assert_duration(5, "Duration for 1 second and 1 frame apart", 25, calculate_duration(tc_in_4, tc_out_4))

# Additional Scenarios with Start TC as 01:00:00:01

# 6. Identical timecodes at 01:00:00:01
tc_in_5 = Timecode(FPS, '01:00:00:01')
tc_out_5 = Timecode(FPS, '01:00:00:01')
assert_duration(6, "Duration for identical timecodes at 01:00:00:01", 1, calculate_duration(tc_in_5, tc_out_5))

# 7. 1 frame from 01:00:00:01 to 01:00:00:02
tc_in_6 = Timecode(FPS, '01:00:00:01')
tc_out_6 = Timecode(FPS, '01:00:00:02')
assert_duration(7, "Duration for 1 frame from 01:00:00:01", 2, calculate_duration(tc_in_6, tc_out_6))

# 8. 2 frames from 01:00:00:01 to 01:00:00:03
tc_in_7 = Timecode(FPS, '01:00:00:01')
tc_out_7 = Timecode(FPS, '01:00:00:03')
assert_duration(8, "Duration for 2 frames from 01:00:00:01", 3, calculate_duration(tc_in_7, tc_out_7))

# 9. 1 second apart from 01:00:00:01 to 01:00:01:00 (24 frames)
tc_in_8 = Timecode(FPS, '01:00:00:01')
tc_out_8 = Timecode(FPS, '01:00:01:00')
assert_duration(9, "Duration for 1 second apart from 01:00:00:01", 24, calculate_duration(tc_in_8, tc_out_8))

# 10. 1 second and 1 frame from 01:00:00:01 to 01:00:01:02 (25 frames)
tc_in_9 = Timecode(FPS, '01:00:00:01')
tc_out_9 = Timecode(FPS, '01:00:01:02')
assert_duration(10, "Duration for 1 second and 1 frame from 01:00:00:01", 25, calculate_duration(tc_in_9, tc_out_9))

print("All tests passed successfully!")


---

This works fine!
I was using the wrong syntax and method.

Results:

PS E:\TimeCode_Tools> & E:/mc/envs/TC/python.exe e:/TimeCode_Tools/002_TEST.py
Scenario 1: Duration for identical timecodes => 1 frames
Scenario 2: Duration for 1 frame => 2 frames
Scenario 3: Duration for 2 frames => 3 frames
Scenario 4: Duration for 1 second apart => 24 frames
Scenario 5: Duration for 1 second and 1 frame apart => 25 frames
Scenario 6: Duration for identical timecodes at 01:00:00:01 => 1 frames
Scenario 7: Duration for 1 frame from 01:00:00:01 => 2 frames
Scenario 8: Duration for 2 frames from 01:00:00:01 => 3 frames
Scenario 9: Duration for 1 second apart from 01:00:00:01 => 24 frames
Scenario 10: Duration for 1 second and 1 frame from 01:00:00:01 => 25 frames
All tests passed successfully!

**Comment by eoyilmaz** [comment]
Hey @jdrx99 what is this all about? TC.frames is the number of `frames` in the given timecode, `frame_number` is basically `frames-1` showing the frame number starting from 0.

Otherwise if you want to extend our test suite by adding more tests, please create a PR.

Many thanks,
